name: push go build/test/publish

on:
  push:

jobs:
  go-build:
    name: go build test fmt check
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      id: checkout
      uses: actions/checkout@master

    - name: Build
      id: build
      run: make container        

    - name: Get git short sha
      id: get_version
      run: echo ::set-env name=SHORT_SHA::$(./hacks/git-version)

    - name: Publish to Registry
      id: publish_to_registry
      if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: shelman/deadman
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: "latest,${{ env.SHORT_SHA }}"
        registry: quay.io

