name: push go build/test/publish

on: [pull_request, push]

jobs:
  go-build:
    name: go build test fmt check
    runs-on: ubuntu-latest
    steps:

    - id: checkout
      uses: actions/checkout@master

    - id: build
      run: make container        

    - id: get_version
      run: echo ::set-env name=SHORT_SHA::$(./hacks/git-version)

    - id: publish_to_registry
      # if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: shelman/deadman
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: "latest,${{ env.SHORT_SHA }}"
        registry: quay.io

    - id: comment_on_pr
      uses: actions/github-script@v2
      if: github.event_name == 'pull_request'
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '👋 docker image quay.io/shelman/deadman:${{ env.SHORT_SHA }}'
          })

