name: push go build/test/publish

on:
  push:

jobs:
  go-build:
    name: go build test fmt check
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@master

    - name: Build
      run: make container        

    - name: Get git short sha
      id: get_version
      run: echo ::set-env name=SHORT_SHA::$(echo ${GITHUB_SHA:8})

    - if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: quay.io/shelman/deadman
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: "latest,${{ env.SHORT_SHA }}"

