name: push go build/test/publish

on: [push]

jobs:
  go-build:
    name: go build test fmt check
    runs-on: ubuntu-latest
    steps:

    - id: checkout
      uses: actions/checkout@master

    - id: get_version
      run: echo ::set-env name=SHORT_SHA::$(./hacks/git-version)

    - id: extract_branch
      shell: bash
      run: echo "::set-env name=BRANCH_NAME::$(echo ${GITHUB_REF#refs/heads/})"

    - id: set_container_tag 
      shell: bash
      run: echo ::set-env name=CONTAINER_TAG::$(echo ${TAG})
      env:
        TAG: "${{ env.BRANCH_NAME }}-${{ env.SHORT_SHA }}"

    - id: build
      run: make container        
      env:
        VERSION: "${{ env.CONTAINER_TAG }}"

    - id: publish_to_registry
      # if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: shelman/deadman
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: "${{ env.CONTAINER_TAG }}"
        registry: quay.io


    - name: comment PR
      if: github.event_name == 'pull_request'
      uses: unsplash/comment-on-pr@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        msg: "👋 docker image quay.io/shelman/deadman:${{ env.CONTAINER_TAG }}"


#    - id: comment_on_pr
#      # if: github.event_name == 'pull_request'
#      uses: actions/github-script@v2
#      with:
#        github-token: ${{secrets.GITHUB_TOKEN}}
#        script: |
#          github.issues.createComment({
#            issue_number: context.issue.number,
#            owner: context.repo.owner,
#            repo: context.repo.repo,
#            body: '👋 docker image quay.io/shelman/deadman:${{ env.CONTAINER_TAG }}'
#          })
#
